// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/camry/dove"
	"godoc/app"
	"godoc/routes"
)

// Injectors from wire.go:

func wireApp() *dove.App {
	echo := routes.NewEcho()
	doveApp := app.NewApp(echo)
	return doveApp
}
