// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/camry/dove"
	"github.com/camry/dove/log"
	"godoc/app"
	"godoc/routes"
)

// Injectors from wire.go:

func wireApp(l log.Logger) *dove.App {
	echo := routes.NewEcho(l)
	doveApp := app.NewApp(echo, l)
	return doveApp
}
